### ISSUE TITLE
Non-threaded handler

### ISSUE THREAD

**Issue by dantmnf** [cinchrb/cinch#186]
Sometimes a simple handler (eg. CTCP VERSION handler) doesn't need a separated thread.
It may be better if we have an option to do that.

**Comment by dominikh** [comment]
Is the separate thread hurting?

To give a somewhat more elaborate answer: For Cinch 2.x I don't see it happening. Primarily because Cinch is in maintenance mode, secondarily because I'm not sure how easy it is to add such an option to the current, somewhat flawed, implementation of handlers.

Maybe if there's ever going to be a Cinch 3, which would be bound to be a rewrite, it will be taken into consideration, even though I still think that it's a pointless optimization, considering that other parts of Cinch are more likely to be the bottleneck than spawning another thread.
