### ISSUE TITLE
":invite" event is not documented

### ISSUE THREAD

**Issue by simnalamburt** [cinchrb/cinch#253]
http://www.rubydoc.info/github/cinchrb/cinch/file/docs/events.md

`:invite` event is not documented. I just had to guess the name of the event.

**Comment by petertseng** [comment]
Sorry for barging in without permission on this issue, I noticed that invite would fall under "Events mapping directly to IRC commands" in http://www.rubydoc.info/github/cinchrb/cinch/file/docs/events.md , since invite is 4.2.7 in https://www.ietf.org/rfc/rfc1459.txt but I am not sure if that should affect things (if there should be an abridged list of possible things falling under the "mapping directly to IRC commands" category, etc etc)

**Comment by simnalamburt** [comment]
@petertseng You're right. Closing this issue
