### ISSUE TITLE
Global nick filter

### ISSUE THREAD

**Issue by jhass** [cinchrb/cinch#78]
Related to #67 I'd like to be able to specify a list of nicks and/or hostmasks that are completely ignored. This would be especially useful to filter other bots or users abusing the bot in any way.

**Comment by green-big-frog** [comment]
+1

**Comment by woodruffw** [comment]
+1

**Comment by dominikh** [comment]
Cinch has support for hooks for dropping messages. One could easily write a module and include that in every plugin class that should abide by the blacklist.

I've used a similar approach for a more complex ACL system here: https://github.com/dominikh/Mathetes/blob/cinch_rewrite/bot.rb

The lines of interest are 3-15. https://github.com/dominikh/Mathetes/blob/cinch_rewrite/lib/cinch/plugins/dictionary.rb for example demonstrates the use of it on line 9. Instead of monkeypatching, one could write a proper mixin, and the "enable_acl" call could be automated with the `included` callback of Ruby.

**Comment by woodruffw** [comment]
Thank you!

**Comment by Namasteh** [comment]
Thank you, that will be really useful.

**Comment by dominikh** [comment]
Closing this issue because it can be implemented by users via the aforementioned filter hook.
